=== M9J/chord-chart/xmldef/chord-chart.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://www.M9J.github.io"
    xmlns="https://www.M9J.github.io"
    elementFormDefault="qualified">
    <xs:element name="chord-chart">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="keyWhite">
                    <xs:complexType>
                        <xs:attribute name="note" type="xs:string" use="required" />
                        <xs:attribute name="isPressed" type="xs:string" use="optional" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="keyBlack">
                    <xs:complexType>
                        <xs:attribute name="note" type="xs:string" use="required" />
                        <xs:attribute name="isPressed" type="xs:string" use="optional" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== M9J/chord-chart/chord-chart/cMajor.xml
<?xml version="1.0" encoding="UTF-8"?>

<chord-chart xmlns="https://m9j.github.io/chord-chart/xmldef"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://m9j.github.io/chord-chart/xmldef chord-chart.xsd">
    <keyWhite note="C" isPressed="Y" />
    <keyBlack note="C" />
    <keyWhite note="D" />
    <keyBlack note="D" />
    <keyWhite note="E" isPressed="Y" />
    <keyWhite note="F" />
    <keyBlack note="F" />
    <keyWhite note="G" isPressed="Y" />
    <keyBlack note="G" />
    <keyWhite note="A" />
    <keyBlack note="A" />
    <keyWhite note="B" />
</chord-chart>
